```xml
<?xml version="1.0" encoding="UTF-8"?>             <!--XML declaration specifying the version and encoding of the XML document.-->

<!-- Project and this is the root element -->
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion> <!--Specifies the version of the POM model being used.-->

<!-- The parent element specifies the parent POM from which this project inherits configuration.-->

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.13</version>
        <relativePath/> <!--Specifies the relative path to the parent POM. An empty value indicates that Maven should look for the parent POM in the local repository or remote repositories.-->
    </parent>

<!-- pom.xml (Project Object Model) is the configuration file for a Maven project. 
It defines the project's metadata, dependencies, Java version, plugins, build configuration, 
and how Maven should build and manage the project.-->

    <groupId>com.investment</groupId> <!--Specifies the group or organization that the project belongs to.-->
    <artifactId>investment-system</artifactId> <!--Specifies the unique identifier for the project within the group.-->
    <version>0.0.1-SNAPSHOT</version> <!--Specifies the version of the project. The "SNAPSHOT" suffix indicates that this is a development version.-->

<!-- We use spring-boot-starter-parent because it provides dependency version management, plugin management, 
and sensible build defaults. This lets us avoid manually configuring versions and build settings.-->

    <name/>
    <description/>
    <url/>

    <licenses>
        <license/>
    </licenses>

    <developers>
        <developer/>
    </developers>

    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

<!-- Project Metadata ends here-->

    <properties>
        <java.version>17</java.version> <!--Specifies the Java version to be used for compiling the project.-->
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>

                <configuration>
                    <annotationProcessorPaths>

                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>

                    </annotationProcessorPaths>
                </configuration>

            </plugin>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>

                <configuration>
                    <excludes>

                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>

                    </excludes>
                </configuration>

            </plugin>

        </plugins>

    </build>

</project>
```
